<?php $data = $block->getAllData();
$countryList=$block->getCountries();
//print_r($countryList);
$name = '';
$email = '';
$telephone = '';
$DOB ='';
$gender='';
$country='';
if ($data->getId()) {
    $name = $data->getName();
    $email = $data->getEmail();
    $telephone = $data->getTelephone();
    //$DOB = $data->getDateAt();
    $DOB =date('d/m/Y', strtotime($data->getDateAt()));
   $gender = $data->getGender();
   $country = $data->getCountry();
}
$countries = array (
    'AF' => 'Afghanistan',
    'AX' => 'Åland Islands',
    'AL' => 'Albania',
    'IN' => 'India',
    'TR' => 'Turkey',
    'US' => 'United states'
    );
?>
<script type="text/javascript">
    require(["jquery", "mage/calendar"], function ($) {
        $('#dob').datepicker({
                prevText: '&#x3c;zurück', prevStatus: '',
                prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                nextText: 'Vor&#x3e;', nextStatus: '',
                nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'],
                monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                dayNames: ['Sunday ', 'Monday', 'Tuesday ', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                showMonthAfterYear: false,
                dateFormat: 'd/m/yy'
            }
        );
    });
</script>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <?php
                    if ($data->getId()) {
                        ?>
                        <input type="hidden" name="id" value="<?php echo $data->getId(); ?>">
                        <?php
                    } ?>
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="<?php echo $name ?>" class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="<?php echo $email; ?>"
                                       class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                                <input name="telephone" id="telephone" title="Telephone"
                                       value="<?php echo $telephone; ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field dob required">
			    <label class="field" for="title">
				<span><?= $block->escapeHtmlAttr(__('DOB')) ?></span>
			    </label>
			    <div class="field-control ">
				<input class="control-text" name="dob" id="dob" type="text" value="<?php echo $DOB ?>">
			    </div>
			</div>
			<div class="field gender required">
			    <label class="field" for="title">
				<span><?= $block->escapeHtmlAttr(__('Gender')) ?></span>
			    </label>
			    <div class="field-control ">
			       Female	<input class="control-text" name="gender" id="gender" type="radio" value="f" <?php if($gender=='f'){ echo 'checked'; } ?>>  Male
				<input class="control-text" name="gender" id="gender" type="radio" value="m" <?php if($gender=='m'){ echo 'checked'; } ?>>
			    </div>
			</div>
			<div class="field country required">
		               <label class="label" for="country"><span><?= $block->escapeHtmlAttr(__('Country')) ?></span></label>
		               <div class="control">
		               
		                           <?php echo $countryList?>
		                           
		               </div>
                     </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Save')) ?></span></button>
                            <button type="button" class="action submit primary" title="show"><a href="<?php echo $this->getUrl('firstunit/index/showdata', ['_secure' => true]) ?>"><span style="color:#FFFFFF;text-align:center;">Show All</span></a></button>
                </div>
            </div>
        </form>
    </div>
</div>
