<?php
 $collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Telephone') ?></th>
            <th scope="col" class="col telephone"><?php echo __('DOB') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Gender') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Country') ?></th>
            <th scope="col" class="col createat"><?php echo __('Createsubmitd At') ?></th>
              <th scope="col" class="col action"><?php echo __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php 
 foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                <?php echo $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                <?php echo $item->getEmail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Telephone')) ?>" class="col telephone">
                <?php echo $item->getTelephone() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('DOB')) ?>" class="col dob">
                <?php 
                //$date1 = strtr($item->getDOB(), '/', '-');
                //$date = DateTime::createFromFormat('Y-m-d H:i:s',$item->getDOB());
                //echo date('Y-m-d', strtotime($date1));
               //echo $date->format('Y-m-d H:i:s');
               echo date('Y-m-d', strtotime($item->getDateAt()))
               //echo $item->getDateAt();
               ?>
            </td>
             <td data-th="<?= $block->escapeHtml(__('Gender')) ?>" class="col dob">
                <?php echo $item->getGender() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Country')) ?>" class="col country">
                <?php echo $item->getCountry() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col delete">
                <a href="<?php echo $block->getDeleteAction() . 'customer_id/' . $item->getId(); ?>"><?php echo __('Delete') ?></a>
                <a style="margin-left: 9px"
                   href="<?php echo $block->getEditAction() . 'customer_id/' . $item->getId(); ?>"><?php echo __('Edit') ?></a>
       
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
 }
 ?>
 <button type="button" class="action submit primary" title="show"><a href="<?php echo $this->getUrl('firstunit/index/index', ['_secure' => true]) ?>"><span style="color:#FFFFFF;text-align:center;">Add New</span></a></button>
